services:
  bot:
    container_name: tggl-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./tggl:/tggl
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M