apiVersion: v1
kind: Secret
metadata:
  name: tggl-secret
type: Opaque
data:
  GITLAB_URL: <insert here your gitlab instance url encoded with base64>
  PRIVATE_TOKEN: <insert here your gitlab private token encoded with base64>
  TEST_JOB_NAME: <insert here test job name encoded with base64>
  PROJECT_ID: <insert here your project encoded with base64>
  TELEGRAM_BOT_TOKEN: <insert here your telegram bot token encoded with base64>
  MR_REGEXP: <insert here regexp to parse MR link encoded with base64>
